(()=>{'use strict';
// Visual layer only: keeps the simulation/state from human-city.js and replaces its rough canvas.
const oldCanvas=[...document.querySelectorAll('canvas')].pop();
if(oldCanvas)oldCanvas.style.display='none';
const oldUi=[...document.body.children].filter(e=>e.tagName==='DIV');oldUi.forEach(e=>e.style.display='none');
document.body.style.margin='0';document.body.style.overflow='hidden';document.body.style.background='#d9e1df';
const canvas=document.createElement('canvas');canvas.style.cssText='position:fixed;inset:0;width:100vw;height:100vh;cursor:grab;display:block';document.body.appendChild(canvas);const ctx=canvas.getContext('2d');
const hud=document.createElement('div');hud.style.cssText='position:fixed;left:22px;top:18px;z-index:10;color:#17201f;pointer-events:none';hud.innerHTML='<div style="font-size:28px;font-weight:900;letter-spacing:5px">MINICITY</div><div id="sub" style="margin-top:5px;font-size:12px;font-weight:700;opacity:.72"></div>';document.body.appendChild(hud);
const legend=document.createElement('div');legend.style.cssText='position:fixed;left:22px;bottom:20px;z-index:10;background:#ffffffdf;border:1px solid #ffffffaa;border-radius:14px;padding:10px 13px;color:#27312f;font:600 11px system-ui;box-shadow:0 8px 25px #0002';legend.innerHTML='RODAS · CASAS · PRAÇA · PARQUE · RIO · 50 HABITANTES';document.body.appendChild(legend);
const panel=document.createElement('div');panel.style.cssText='position:fixed;right:20px;top:20px;width:315px;max-height:78vh;overflow:auto;z-index:12;background:#17201fee;color:#fff;border-radius:18px;padding:18px;box-shadow:0 18px 50px #0005;font:13px system-ui;display:none';document.body.appendChild(panel);
const buttons=document.createElement('div');buttons.style.cssText='position:fixed;right:20px;bottom:20px;z-index:13;display:flex;gap:8px';buttons.innerHTML='<button id="pause">PAUSAR</button><button id="reset">NOVO MUNDO</button>';document.body.appendChild(buttons);buttons.querySelectorAll('button').forEach(b=>b.style.cssText='border:0;border-radius:10px;padding:11px 14px;background:#17201f;color:white;font-weight:800;box-shadow:0 7px 20px #0003');
let DPR=1,zoom=1.08,panX=0,panY=45,drag=false,lx=0,ly=0,selected=null,paused=false,people=[],houses=[],world={};
const A=Math.PI/4,T=.56,G=0;
function resize(){DPR=devicePixelRatio||1;canvas.width=innerWidth*DPR;canvas.height=innerHeight*DPR;ctx.setTransform(DPR,0,0,DPR,0,0);draw()}addEventListener('resize',resize);
function P(x,y,z){const dx=x*Math.cos(A)-z*Math.sin(A),dz=x*Math.sin(A)+z*Math.cos(A);return[innerWidth/2+panX+dx*zoom*5,innerHeight/2+panY+(dz*T-y)*zoom*5]}
function poly(a,c){ctx.fillStyle=c;ctx.beginPath();a.forEach((p,i)=>i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]));ctx.closePath();ctx.fill()}
function stroke(a,b,c,w=1){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}
function rectGround(x1,z1,x2,z2,c){poly([P(x1,G,z1),P(x2,G,z1),P(x2,G,z2),P(x1,G,z2)],c)}
function load(){try{const s=JSON.parse(localStorage.getItem('MINICITY_WORLD')||'null');if(s&&Array.isArray(s.people)){people=s.people;houses=s.houses||[];world=s.world||{}}}catch(e){}if(!people.length)people=Array.from({length:50},(_,i)=>({id:i,name:'Habitante '+(i+1),x:-60+(i%10)*13,z:-35+Math.floor(i/10)*14,age:20+i%40,money:10,goal:'explorar',task:'observando',trait:'curioso',inventory:{}}));}
function roadH(z){rectGround(-82,z-5,82,z+5,'#555957');rectGround(-82,z-8,-82,z+8,'#c5c2b8');rectGround(82,z-8,82,z+8,'#c5c2b8');for(let q=-74;q<74;q+=13)stroke(P(q,.02,z),P(q+6,.02,z),'#dfcf8b',1.5)}
function roadV(x){rectGround(x-5,-66,x+5,66,'#555957');rectGround(x-8,-66,x-5,66,'#c5c2b8');rectGround(x+5,-66,x+8,66,'#c5c2b8');for(let q=-58;q<58;q+=13)stroke(P(x,.02,q),P(x,.02,q+6),'#dfcf8b',1.5)}
function crosswalk(x,z,h){for(let i=-3;i<=3;i++)rectGround(x+i*1.8,z-5,x+i*1.8+1,z+5,'#e8e4d8')}
function building(h){const x=h.x||0,z=h.z||0,w=(h.w||5)*1.9,d=(h.w||5)*1.35,H=(h.h||5)*2.1;const a=P(x-w/2,G,z-d/2),b=P(x+w/2,G,z-d/2),c=P(x+w/2,G,z+d/2),d0=P(x-w/2,G,z+d/2);const top=[P(x-w/2,H,z-d/2),P(x+w/2,H,z-d/2),P(x+w/2,H,z+d/2),P(x-w/2,H,z+d/2)];poly([a,b,top[1],top[0]],h.wall||'#d3ae87');poly([b,c,top[2],top[1]],'#b6876e');poly([c,d0,top[3],top[2]],'#c49b76');poly([d0,a,top[0],top[3]],'#d8bb91');poly([top[0],top[1],top[2],top[3]],h.roof||'#76594c');
const door=P(x,G+.02,z+d/2+.02);const dp=P(x,G+H*.48,z+d/2+.03);ctx.fillStyle='#634536';ctx.fillRect(door[0]-5*zoom,door[1]-18*zoom,10*zoom,18*zoom);for(const side of [-1,1]){const q=P(x+side*w*.25,H*.42,z+d/2+.04);ctx.fillStyle='#a9d3d4';ctx.fillRect(q[0]-6*zoom,q[1]-7*zoom,12*zoom,7*zoom)}if(h.shop){const q=P(x,G+H*.72,z+d/2+.05);ctx.fillStyle='#f0d26f';ctx.fillRect(q[0]-28*zoom,q[1]-7*zoom,56*zoom,14*zoom);ctx.fillStyle='#40372d';ctx.font=`800 ${8*zoom}px system-ui`;ctx.textAlign='center';ctx.fillText(h.shop,q[0],q[1]+3*zoom)}}
function tree(x,z){const q=P(x,G,z),s=zoom;ctx.fillStyle='#75503a';ctx.fillRect(q[0]-2*s,q[1]-17*s,4*s,17*s);ctx.fillStyle='#3f6f49';ctx.beginPath();ctx.arc(q[0],q[1]-25*s,12*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#6c9658';ctx.beginPath();ctx.arc(q[0]-7*s,q[1]-29*s,8*s,0,Math.PI*2);ctx.fill();}
function lamp(x,z){const q=P(x,G,z),s=zoom;stroke([q[0],q[1]],[q[0],q[1]-22*s],'#303532',2);ctx.fillStyle='#ffe49b';ctx.beginPath();ctx.arc(q[0],q[1]-24*s,3*s,0,Math.PI*2);ctx.fill()}
function person(p){const s=zoom*(.76+(p.id%4)*.035),q=P(p.x||0,G,p.z||0),phase=(performance.now()/150+(p.id||0)*.9),walk=Math.sin(phase)*5;let dx=p.dirX||1,dz=p.dirZ||0,l=Math.hypot(dx,dz)||1;dx/=l;dz/=l;const a=P((p.x||0)+dx,G,(p.z||0)+dz),ux=(a[0]-q[0]),uy=(a[1]-q[1]),ll=Math.hypot(ux,uy)||1,fx=ux/ll,fy=uy/ll,rx=-fy,ry=fx;function pt(side,up){return[q[0]+(rx*side+fx*up)*s,q[1]+(ry*side+fy*up)*s]}function limb(a,b,c,w){stroke(pt(a[0],a[1]),pt(b[0],b[1]),c,w*s)}const skin=['#d49b78','#a96f50','#efbd95','#8b5d45'][p.id%4],shirt=['#47709d','#b85b4d','#5c855f','#b78b42','#765b94'][p.id%5],pant=['#26384d','#45433f','#513e35'][p.id%3];ctx.save();ctx.shadowColor='#0004';ctx.shadowBlur=3;ctx.shadowOffsetY=2;limb([-6,-12],[-8+walk,-2],pant,6);limb([-8+walk,-2],[-7-walk,13],pant,4.5);limb([6,-12],[8-walk,-2],pant,6);limb([8-walk,-2],[7+walk,13],pant,4.5);limb([-8,-30],[-14-walk*.6,-18],shirt,6);limb([-14-walk*.6,-18],[-16-walk,-5],skin,4);limb([8,-30],[14+walk*.6,-18],shirt,6);limb([14+walk*.6,-18],[16+walk,-5],skin,4);poly([pt(-9,-31),pt(9,-31),pt(8,-10),pt(-8,-10)],shirt);ctx.fillStyle=skin;ctx.beginPath();ctx.arc(pt(0,-42)[0],pt(0,-42)[1],7.5*s,0,Math.PI*2);ctx.fill();ctx.fillStyle='#30221c';ctx.beginPath();ctx.arc(pt(0,-44)[0],pt(0,-44)[1],7.7*s,Math.PI,Math.PI*2);ctx.fill();ctx.restore();if(selected===p){ctx.strokeStyle='#fff';ctx.lineWidth=2;ctx.beginPath();ctx.ellipse(q[0],q[1]-23*s,16*s,31*s,0,0,Math.PI*2);ctx.stroke()}}
function panelFor(p){selected=p;panel.style.display='block';const inv=p.inventory||{};panel.innerHTML=`<div style="font-size:20px;font-weight:900">${p.name||'Habitante'}</div><div style="opacity:.65;margin:3px 0 15px">ID ${p.id??'-'} · ${p.alive===false?'MORTO':'VIVO'}</div><div style="line-height:1.75"><b>Idade:</b> ${p.age??'-'}<br><b>Objetivo:</b> ${p.goal||'-'}<br><b>O que faz:</b> ${p.task||'-'}<br><b>Destino:</b> ${p.destination||'-'}<br><b>Personalidade:</b> ${p.trait||'-'}<br><b>Dinheiro:</b> ${p.money??0}<br><b>Casa:</b> ${p.home==null?'sem casa':'casa #'+p.home}<br><b>Conhecimento:</b> ${(p.knowledge||[]).join(', ')||'ainda pouco'}<br><b>Memórias:</b> ${(p.memory||[]).length}<br><b>Inventário:</b> ${Object.entries(inv).map(([k,v])=>k+': '+v).join(' · ')||'vazio'}</div>`;draw()}
function terrain(){rectGround(-90,-72,90,72,'#9db487');rectGround(-25,30,25,65,'#86a66d');rectGround(52,-65,82,-20,'#4d8ca0');rectGround(-82,18,-52,58,'#86a66d');roadH(-30);roadH(0);roadH(30);roadV(-45);roadV(0);roadV(45);crosswalk(-45,0);crosswalk(0,0);crosswalk(45,0);rectGround(-22,-21,22,21,'#a9a47d');ctx.fillStyle='#78926b';const q=P(0,G,0);ctx.beginPath();ctx.arc(q[0],q[1]-2,28*zoom,0,Math.PI*2);ctx.fill();for(let i=0;i<16;i++)tree(-66+(i%4)*44,-54+Math.floor(i/4)*36);for(let i=0;i<14;i++)lamp(-36+(i%7)*12,-9+Math.floor(i/7)*18);for(let i=0;i<6;i++){const q=P(-15+i*6,G,42);ctx.fillStyle='#5f6c55';ctx.fillRect(q[0]-2,q[1]-8,4,8)}}
function draw(){load();ctx.clearRect(0,0,innerWidth,innerHeight);terrain();const objs=[];houses.forEach(h=>objs.push({z:(h.z||0)+(h.w||5),type:'house',v:h}));people.forEach(p=>objs.push({z:p.z||0,type:'person',v:p}));objs.sort((a,b)=>a.z-b.z);objs.forEach(o=>o.type==='house'?building(o.v):person(o.v));const sub=document.getElementById('sub');sub.textContent=`ANO ${world.year||1} · DIA ${world.day||0} · ${people.filter(p=>p.alive!==false).length} HABITANTES · ${world.discoveries?.length||0} DESCOBERTAS`;if(!paused)requestAnimationFrame(draw)}
canvas.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(2.8,zoom*(e.deltaY<0?1.08:.92)));draw()},{passive:false});canvas.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY;canvas.style.cursor='grabbing'});addEventListener('pointerup',()=>{drag=false;canvas.style.cursor='grab'});addEventListener('pointermove',e=>{if(!drag)return;panX+=e.clientX-lx;panY+=e.clientY-ly;lx=e.clientX;ly=e.clientY;draw()});canvas.addEventListener('click',e=>{if(drag)return;let hit=null,best=999;people.forEach(p=>{const q=P(p.x||0,G,p.z||0),d=Math.hypot(e.clientX-q[0],e.clientY-q[1]);if(d<best&&d<26*zoom){best=d;hit=p}});if(hit)panelFor(hit)});
document.getElementById('pause').onclick=()=>{paused=!paused;document.getElementById('pause').textContent=paused?'CONTINUAR':'PAUSAR';draw()};document.getElementById('reset').onclick=()=>{if(confirm('Criar um mundo novo e apagar o estado atual?')){localStorage.removeItem('MINICITY_WORLD');location.reload()}};
resize();draw();
})();