(()=>{'use strict';
const oldCanvas=document.querySelector('canvas');if(oldCanvas)oldCanvas.style.display='none';[...document.body.children].forEach(e=>{if(e.tagName==='DIV')e.style.display='none'});
document.body.style.cssText='margin:0;overflow:hidden;background:#cfd8d5;font-family:Inter,system-ui,sans-serif';
const c=document.createElement('canvas');c.style.cssText='position:fixed;inset:0;width:100vw;height:100vh;display:block;cursor:grab';document.body.appendChild(c);const g=c.getContext('2d');
const hud=document.createElement('div');hud.style.cssText='position:fixed;left:24px;top:20px;z-index:20;color:#17211f;pointer-events:none';hud.innerHTML='<div style="font-size:30px;font-weight:950;letter-spacing:5px">MINICITY</div><div id="stats" style="margin-top:4px;font-size:12px;font-weight:750;opacity:.72"></div>';document.body.appendChild(hud);
const card=document.createElement('div');card.style.cssText='position:fixed;right:22px;top:20px;width:315px;max-height:76vh;overflow:auto;z-index:25;background:rgba(20,29,28,.94);color:#fff;border:1px solid #ffffff22;border-radius:18px;padding:18px;box-shadow:0 20px 60px #0005;font-size:13px;display:none';document.body.appendChild(card);
const tools=document.createElement('div');tools.style.cssText='position:fixed;right:22px;bottom:20px;z-index:25;display:flex;gap:8px';tools.innerHTML='<button id="pause">PAUSAR</button><button id="reset">NOVO MUNDO</button>';document.body.appendChild(tools);tools.querySelectorAll('button').forEach(b=>b.style.cssText='border:0;border-radius:11px;padding:11px 16px;background:#16201e;color:#fff;font-weight:850;box-shadow:0 8px 24px #0004;cursor:pointer');
const note=document.createElement('div');note.style.cssText='position:fixed;left:22px;bottom:20px;z-index:20;background:#ffffffdf;border:1px solid #fff;border-radius:13px;padding:9px 12px;color:#34403c;font-size:11px;font-weight:750;box-shadow:0 8px 25px #0002';note.textContent='RODAS · CALÇADAS · CASAS · PRAÇA · PARQUE · RIO · 50 HABITANTES';document.body.appendChild(note);
let dpr=1,zoom=1.05,panX=0,panY=50,drag=false,moved=false,lx=0,ly=0,selected=null,paused=false,state={people:[],houses:[],world:{},year:1,day:0};
const A=Math.PI/4,T=.57,G=0;
const skins=['#d39a77','#ad704f','#efbd96','#895a43'],shirts=['#426c9a','#b65a4e','#56805c','#bd9348','#75588f','#3d7e83'],pants=['#293a4e','#44433f','#543f36','#344c5a'];
function resize(){dpr=devicePixelRatio||1;c.width=innerWidth*dpr;c.height=innerHeight*dpr;g.setTransform(dpr,0,0,dpr,0,0)}addEventListener('resize',resize);
function P(x,y,z){const dx=x*Math.cos(A)-z*Math.sin(A),dz=x*Math.sin(A)+z*Math.cos(A);return[innerWidth/2+panX+dx*zoom*5,innerHeight/2+panY+(dz*T-y)*zoom*5]}
function poly(a,col){g.fillStyle=col;g.beginPath();a.forEach((p,i)=>i?g.lineTo(p[0],p[1]):g.moveTo(p[0],p[1]));g.closePath();g.fill()}
function line(a,b,col,w=1){g.strokeStyle=col;g.lineWidth=w;g.lineCap='round';g.beginPath();g.moveTo(a[0],a[1]);g.lineTo(b[0],b[1]);g.stroke()}
function plane(x1,z1,x2,z2,col){poly([P(x1,G,z1),P(x2,G,z1),P(x2,G,z2),P(x1,G,z2)],col)}
function load(){try{const s=JSON.parse(localStorage.getItem('MINICITY_WORLD')||'null');if(s){state=s;state.people=Array.isArray(s.people)?s.people:[];state.houses=Array.isArray(s.houses)?s.houses:[];state.world=s.world||{}}}catch(e){}if(!state.people.length)state.people=Array.from({length:50},(_,i)=>({id:i,name:'Habitante '+(i+1),x:-70+(i%10)*14,z:-42+Math.floor(i/10)*16,age:20+i%40,goal:'explorar',task:'observando',trait:'curioso',money:10,inventory:{}}))}
function roadH(z){plane(-84,z-5,84,z+5,'#505452');plane(-84,z-8,-84,z+8,'#c8c5bd');plane(84,z-8,84,z+8,'#c8c5bd');for(let q=-77;q<77;q+=14)line(P(q,.04,z),P(q+7,.04,z),'#e2d38f',1.6)}
function roadV(x){plane(x-5,-70,x+5,70,'#505452');plane(x-8,-70,x-5,70,'#c8c5bd');plane(x+5,-70,x+8,70,'#c8c5bd');for(let q=-63;q<63;q+=14)line(P(x,.04,q),P(x,.04,q+7),'#e2d38f',1.6)}
function cross(x,z){for(let i=-3;i<=3;i++)plane(x+i*1.8,z-5,x+i*1.0+1,z+5,'#eee9dc')}
function tree(x,z,scale=1){const q=P(x,G,z),s=zoom*scale;g.fillStyle='#73503b';g.fillRect(q[0]-2*s,q[1]-17*s,4*s,17*s);g.fillStyle='#315e40';g.beginPath();g.arc(q[0],q[1]-25*s,13*s,0,7);g.fill();g.fillStyle='#5f8e55';g.beginPath();g.arc(q[0]-7*s,q[1]-30*s,9*s,0,7);g.fill();g.fillStyle='#7fa660';g.beginPath();g.arc(q[0]+7*s,q[1]-27*s,7*s,0,7);g.fill()}
function lamp(x,z){const q=P(x,G,z),s=zoom;line([q[0],q[1]],[q[0],q[1]-24*s],'#303632',2);g.fillStyle='#ffe59c';g.shadowColor='#ffe59c';g.shadowBlur=8*s;g.beginPath();g.arc(q[0],q[1]-26*s,3*s,0,7);g.fill();g.shadowBlur=0}
function building(h){const X=h.x||0,Z=h.z||0,W=(h.w||5)*1.9,D=(h.w||5)*1.35,H=(h.h||5)*2.05;const b1=P(X-W/2,G,Z-D/2),b2=P(X+W/2,G,Z-D/2),b3=P(X+W/2,G,Z+D/2),b4=P(X-W/2,G,Z+D/2),t1=P(X-W/2,H,Z-D/2),t2=P(X+W/2,H,Z-D/2),t3=P(X+W/2,H,Z+D/2),t4=P(X-W/2,H,Z+D/2);g.fillStyle='#0003';g.beginPath();g.ellipse(P(X,G,Z)[0],P(X,G,Z)[1]+4,Math.max(20,W*zoom*1.7),8*zoom,0,0,7);g.fill();poly([b1,b2,t2,t1],h.wall||'#d5b38b');poly([b2,b3,t3,t2],'#b8846d');poly([b3,b4,t4,t3],'#c59b75');poly([b4,b1,t1,t4],'#dfc39a');poly([t1,t2,t3,t4],h.roof||'#76594c');
const s=zoom,door=P(X,G+.02,Z+D/2+.02);g.fillStyle='#604331';g.fillRect(door[0]-5*s,door[1]-19*s,10*s,19*s);for(const side of [-1,1]){const q=P(X+side*W*.25,H*.43,Z+D/2+.04);g.fillStyle='#9eced0';g.fillRect(q[0]-7*s,q[1]-7*s,14*s,7*s);g.fillStyle='#6d8c8d';g.fillRect(q[0],q[1]-7*s,1*s,7*s)}if((h.h||0)>5){const q=P(X+W*.2,H,Z);g.fillStyle='#684a3c';g.fillRect(q[0]-3*s,q[1]-16*s,6*s,16*s);g.fillStyle='#b3a28d';g.fillRect(q[0]-5*s,q[1]-20*s,10*s,5*s)}if(h.shop){const q=P(X,G+H*.72,Z+D/2+.05);g.fillStyle='#f0d36d';g.fillRect(q[0]-30*s,q[1]-8*s,60*s,15*s);g.fillStyle='#3d352c';g.font=`900 ${8*s}px system-ui`;g.textAlign='center';g.fillText(h.shop,q[0],q[1]+3*s)}}
function person(p){const s=zoom*(.78+(p.id%4)*.035),q=P(p.x||0,G,p.z||0),t=performance.now()/145+(p.id||0)*.8,w=Math.sin(t)*4.5;let dx=p.dirX||1,dz=p.dirZ||0,L=Math.hypot(dx,dz)||1;dx/=L;dz/=L;const a=P((p.x||0)+dx,G,(p.z||0)+dz),ux=a[0]-q[0],uy=a[1]-q[1],ll=Math.hypot(ux,uy)||1,fx=ux/ll,fy=uy/ll,rx=-fy,ry=fx;function pt(side,up){return[q[0]+(rx*side+fx*up)*s,q[1]+(ry*side+fy*up)*s]}function limb(a,b,col,wid){line(pt(a[0],a[1]),pt(b[0],b[1]),col,wid*s)}const skin=skins[p.id%skins.length],shirt=shirts[p.id%shirts.length],pant=pants[p.id%pants.length];g.save();g.shadowColor='#0005';g.shadowBlur=3;g.shadowOffsetY=2;limb([-7,-11],[-8+w,-1],pant,6);limb([-8+w,-1],[-7-w,13],pant,4.5);limb([7,-11],[8-w,-1],pant,6);limb([8-w,-1],[7+w,13],pant,4.5);limb([-8,-30],[-14-w*.6,-18],shirt,6);limb([-14-w*.6,-18],[-16-w,-5],skin,4);limb([8,-30],[14+w*.6,-18],shirt,6);limb([14+w*.6,-18],[16+w,-5],skin,4);poly([pt(-9,-31),pt(9,-31),pt(8,-10),pt(-8,-10)],shirt);g.fillStyle=skin;g.beginPath();g.arc(pt(0,-42)[0],pt(0,-42)[1],7.5*s,0,7);g.fill();g.fillStyle='#2c211b';g.beginPath();g.arc(pt(0,-44)[0],pt(0,-44)[1],7.7*s,Math.PI,7);g.fill();g.restore();if(selected===p){g.strokeStyle='#fff';g.lineWidth=2;g.beginPath();g.ellipse(q[0],q[1]-23*s,17*s,32*s,0,0,7);g.stroke()}}
function water(){plane(52,-66,84,-20,'#4d8fa2');for(let i=0;i<7;i++){const z=-61+i*6,q=P(53,G+.03,z);line([q[0],q[1]],[q[0]+35*zoom,q[1]-8*zoom],'#8fc0c7',1)}}
function plaza(){plane(-23,-22,23,22,'#aaa47c');const q=P(0,G,0),s=zoom;g.fillStyle='#d0c7a7';g.beginPath();g.arc(q[0],q[1]-2,25*s,0,7);g.fill();g.fillStyle='#777f72';g.beginPath();g.arc(q[0],q[1]-4,5*s,0,7);g.fill();for(let i=0;i<8;i++){const a=i*Math.PI/4,tx=Math.cos(a)*18,tz=Math.sin(a)*18;tree(tx,tz,.55)}}
function terrain(){const h=(performance.now()/90000)%1;const night=Math.max(0,Math.sin((h-.25)*Math.PI*2)*.42);g.clearRect(0,0,innerWidth,innerHeight);const grad=g.createLinearGradient(0,0,0,innerHeight);grad.addColorStop(0,night>.15?'#465766':'#b8d1d1');grad.addColorStop(1,night>.15?'#899895':'#dce3db');g.fillStyle=grad;g.fillRect(0,0,innerWidth,innerHeight);plane(-92,-76,92,76,night>.15?'#70866e':'#a4b88b');water();roadH(-30);roadH(0);roadH(30);roadV(-45);roadV(0);roadV(45);cross(-45,0);cross(0,0);cross(45,0);plaza();for(let i=0;i<18;i++)tree(-72+(i%6)*28,-56+Math.floor(i/6)*28,.8+(i%3)*.08);for(let i=0;i<18;i++)lamp(-36+(i%9)*9,-9+Math.floor(i/9)*18);}
function panelFor(p){selected=p;card.style.display='block';const inv=p.inventory||{},mem=p.memory||[],know=p.knowledge||[];card.innerHTML=`<div style="font-size:21px;font-weight:900">${p.name||'Habitante'}</div><div style="opacity:.55;margin:3px 0 14px">ID ${p.id??'-'} · ${p.alive===false?'MORTO':'VIVO'}</div><div style="line-height:1.8"><b>Idade:</b> ${p.age??'-'}<br><b>Objetivo:</b> ${p.goal||'-'}<br><b>Tarefa:</b> ${p.task||'-'}<br><b>Destino:</b> ${p.destination||'-'}<br><b>Personalidade:</b> ${p.trait||'-'}<br><b>Dinheiro:</b> ${p.money??0}<br><b>Casa:</b> ${p.home==null?'sem casa':'casa #'+p.home}<br><b>Conhecimento:</b> ${know.join(', ')||'nenhum registrado'}<br><b>Memórias:</b> ${mem.length}<br><b>Inventário:</b> ${Object.entries(inv).map(([k,v])=>k+': '+v).join(' · ')||'vazio'}</div>`}
function draw(){load();terrain();const all=[];state.houses.forEach(h=>all.push({z:(h.z||0)+(h.w||5),k:0,v:h}));state.people.forEach(p=>all.push({z:p.z||0,k:1,v:p}));all.sort((a,b)=>a.z-b.z||a.k-b.k);all.forEach(o=>o.k?person(o.v):building(o.v));const alive=state.people.filter(p=>p.alive!==false).length;document.getElementById('stats').textContent=`ANO ${state.year||1} · DIA ${state.day||0} · ${alive} HABITANTES · ${(state.world.discoveries||[]).length} DESCOBERTAS`;if(!paused)requestAnimationFrame(draw)}
c.addEventListener('wheel',e=>{e.preventDefault();zoom=Math.max(.65,Math.min(3,zoom*(e.deltaY<0?1.08:.92)));draw()},{passive:false});c.addEventListener('pointerdown',e=>{drag=true;moved=false;lx=e.clientX;ly=e.clientY;c.style.cursor='grabbing'});addEventListener('pointerup',()=>{drag=false;c.style.cursor='grab'});addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-lx,dy=e.clientY-ly;if(Math.abs(dx)+Math.abs(dy)>2)moved=true;panX+=dx;panY+=dy;lx=e.clientX;ly=e.clientY;draw()});c.addEventListener('click',e=>{if(moved)return;let hit=null,best=1e9;state.people.forEach(p=>{const q=P(p.x||0,G,p.z||0),d=Math.hypot(e.clientX-q[0],e.clientY-q[1]);if(d<best&&d<30*zoom){best=d;hit=p}});if(hit)panelFor(hit)});
const originalPause=document.getElementById('p'),originalReset=document.getElementById('n');document.getElementById('pause').onclick=()=>{if(originalPause)originalPause.click();paused=!paused;document.getElementById('pause').textContent=paused?'CONTINUAR':'PAUSAR';draw()};document.getElementById('reset').onclick=()=>{if(originalReset)originalReset.click();else{localStorage.removeItem('MINICITY_WORLD');location.reload()}};
resize();draw();setInterval(()=>{if(!paused)load()},1000);
})();