(()=>{'use strict';
const old=document.getElementById('world');if(old)old.style.display='none';document.body.innerHTML='';document.body.style='margin:0;overflow:hidden;background:#9bbecb;font-family:system-ui';
const c=document.createElement('canvas');c.style='position:fixed;inset:0;width:100vw;height:100vh';document.body.appendChild(c);const x=c.getContext('2d');
const ui=document.createElement('div');ui.style='position:fixed;left:18px;top:16px;color:#fff;text-shadow:0 2px 5px #000;z-index:3';ui.innerHTML='<b style="font-size:27px;letter-spacing:.12em">MINICITY</b><br>50 HABITANTES • VILA EM EVOLUÇÃO • 3D';document.body.appendChild(ui);
const panel=document.createElement('div');panel.style='position:fixed;left:18px;bottom:18px;padding:12px 15px;background:#07110ddd;color:#fff;border-radius:10px;z-index:3;font-size:13px;min-width:300px';panel.innerHTML='<b>MINICITY</b><br>Ruas construídas • casas • moradores andando<br>Arraste para girar • roda para aproximar';document.body.appendChild(panel);
const controls=document.createElement('div');controls.style='position:fixed;right:18px;bottom:18px;z-index:3';controls.innerHTML='<button id="p">PAUSAR</button> <button id="n">NOVO MUNDO</button>';document.body.appendChild(controls);controls.querySelectorAll('button').forEach(b=>b.style='padding:10px 14px;border:0;border-radius:8px;background:#18251b;color:#fff;font-weight:800');
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);
const names=['Ana','Bruno','Clara','Davi','Elena','Felipe','Gabriela','Hugo','Iara','Joao','Karina','Leo','Marta','Nuno','Olivia','Paulo','Rita','Sofia','Tiago','Vera','Yara','Zeca','Alice','Bia','Caio','Diana','Eva','Fabi','Gabi','Heitor','Ines','Julia','Lia','Miguel','Nina','Otavio','Pietro','Raquel','Sara','Theo','Ursula','Vitor','Wanda','Xavier','Yasmin','Zoe','Arthur','Beatriz','Celia','Diego'];
let az=.68,dist=58,drag=false,lx=0,t=0,paused=false,selected=null;
function P(X,Y,Z){const ca=Math.cos(az),sa=Math.sin(az),rx=X*ca-Z*sa,rz=X*sa+Z*ca,scale=dist/(dist+rz+82);return [innerWidth/2+rx*scale*6,innerHeight/2+(Y-4)*scale*6,scale]}
function line(a,b,w,color){x.strokeStyle=color;x.lineWidth=w;x.lineCap='round';x.beginPath();x.moveTo(a[0],a[1]);x.lineTo(b[0],b[1]);x.stroke()}
function poly(points,color){x.fillStyle=color;x.beginPath();points.forEach((p,i)=>i?x.lineTo(p[0],p[1]):x.moveTo(p[0],p[1]));x.closePath();x.fill()}
function groundRoad(X1,Z1,X2,Z2,width,color){const a=P(X1,0,Z1),b=P(X2,0,Z2),dx=b[0]-a[0],dy=b[1]-a[1],l=Math.hypot(dx,dy),nx=-dy/l*width,ny=dx/l*width;poly([[a[0]+nx,a[1]+ny],[b[0]+nx,b[1]+ny],[b[0]-nx,b[1]-ny],[a[0]-nx,a[1]-ny]],color)}
function house(h){const q=P(h.x,0,h.z),s=q[2],w=h.w*s*3,d=h.d*s*3,hg=h.h*s*3; x.fillStyle='#8d755f';x.fillRect(q[0]-w,q[1]-hg,w*2,hg);poly([[q[0]-w-2*s,q[1]-hg],[q[0],q[1]-(hg+18*s)],[q[0]+w+2*s,q[1]-hg]],h.roof);x.fillStyle='#5c4338';x.fillRect(q[0]-5*s,q[1]-14*s,10*s,14*s);x.fillStyle='#b7d8df';x.fillRect(q[0]-w*.65,q[1]-hg*.62,9*s,8*s);x.fillRect(q[0]+w*.35,q[1]-hg*.62,9*s,8*s)}
const streets=[{x:0,z:0,type:'main'},{x:-17,z:0},{x:17,z:0},{x:0,z:-16},{x:0,z:16}];
const routes=[];for(let i=0;i<10;i++){const side=i%4, lane=(i%3-1)*7;routes.push(side===0?{x:-48,z:lane}:{x:48,z:lane});routes.push(side===1?{x:lane,z:-38}:{x:lane,z:38})}
const houses=Array.from({length:10},(_,i)=>{const row=Math.floor(i/5),col=i%5;return{x:(col-2)*15,z:(row?13:-13),w:5,d:5,h:4.5+(i%3),roof:['#a64f43','#5d6f57','#8a6648'][i%3]}});
const waypoints=[[-48,0],[-17,0],[0,0],[17,0],[48,0],[0,-38],[0,-16],[0,16],[0,38],[-17,-16],[17,-16],[-17,16],[17,16],[-32,-16],[-32,16],[32,-16],[32,16]];
const people=names.map((name,i)=>{const q=waypoints[i%waypoints.length];return{name,i,x:q[0]+(i%3-1)*1.2,z:q[1]+(i%2?1:-1),target:(i+3)%waypoints.length,speed:.025+(i%5)*.004,phase:i*.71,step:0}});
function chooseTarget(p){p.target=(p.target+1+(p.i%4===0?1:0))%waypoints.length}
function human(p){const q=P(p.x,0,p.z),s=q[2],sx=q[0],sy=q[1],w=Math.sin(t*5+p.phase),skin=['#d49b78','#8d6049','#efbe9a','#b87856','#a56d50'][p.i%5],shirt=['#365d91','#9b453c','#477754','#b88a43','#76548d'][p.i%5],pants=['#29394b','#4a4945','#583e35','#334c5e'][p.i%4];function L(x1,y1,x2,y2,col,ww){line([sx+x1*s,sy+y1*s],[sx+x2*s,sy+y2*s],ww*s,col)}L(-6,-18,-10-w*2,-9,shirt,4);L(6,-18,10+w*2,-9,shirt,4);L(-10-w*2,-9,-11-w*2,-1,skin,3);L(10+w*2,-9,11+w*2,-1,skin,3);L(-4,0,-5+w*3,10,pants,5);L(4,0,5-w*3,10,pants,5);L(-5+w*3,10,-5+w*3,19,pants,4);L(5-w*3,10,5-w*3,19,pants,4);L(-5+w*3,19,-7+w*3,20,'#202020',4);L(5-w*3,19,7-w*3,20,'#202020',4);x.fillStyle=shirt;x.beginPath();x.ellipse(sx,sy-8*s,7*s,9*s,0,0,7);x.fill();x.fillStyle=skin;x.beginPath();x.arc(sx,sy-25*s,6*s,0,7);x.fill();x.fillStyle='#201a17';x.beginPath();x.arc(sx,sy-28*s,6*s,Math.PI,Math.PI*2);x.fill();if(selected===p){x.strokeStyle='#fff';x.lineWidth=2;x.beginPath();x.arc(sx,sy-15*s,12*s,0,7);x.stroke()}}
function tree(X,Z){const q=P(X,0,Z),s=q[2];x.fillStyle='#654831';x.fillRect(q[0]-2*s,q[1]-18*s,4*s,18*s);x.fillStyle='#397044';x.beginPath();x.arc(q[0],q[1]-22*s,13*s,0,7);x.fill()}
function world(){x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='#82ad68';x.fillRect(0,0,innerWidth,innerHeight);const river=P(58,0,0);x.fillStyle='#4b94bb';x.fillRect(river[0]-30,0,60,innerHeight);groundRoad(-60,0,60,0,17,'#65584c');groundRoad(-17,-40,-17,40,13,'#74665a');groundRoad(17,-40,17,40,13,'#74665a');groundRoad(-45,-16,45,-16,10,'#796b5e');groundRoad(-45,16,45,16,10,'#796b5e');groundRoad(0,-38,0,38,13,'#6f6257');groundRoad(-60,-16,60,-16,2,'#9c8a75');groundRoad(-60,16,60,16,2,'#9c8a75');for(let i=0;i<42;i++){const a=i*2.4,r=47+(i%5)*4;tree(Math.cos(a)*r,Math.sin(a)*r)}houses.slice().sort((a,b)=>a.z-b.z).forEach(house);people.slice().sort((a,b)=>a.z-b.z).forEach(human)}
function update(){people.forEach(p=>{const q=waypoints[p.target],dx=q[0]-p.x,dz=q[1]-p.z,d=Math.hypot(dx,dz);if(d<1.3){chooseTarget(p);return}p.x+=dx/d*p.speed;p.z+=dz/d*p.speed;p.step+=.12})}
function save(){try{localStorage.setItem('MINICITY_V7',JSON.stringify(people.map(p=>({x:p.x,z:p.z,target:p.target}))));}catch(e){}}try{const s=JSON.parse(localStorage.getItem('MINICITY_V7'));if(s?.length===50)s.forEach((q,i)=>{people[i].x=q.x;people[i].z=q.z;people[i].target=q.target??people[i].target})}catch(e){}
controls.querySelector('#p').onclick=()=>{paused=!paused;controls.querySelector('#p').textContent=paused?'CONTINUAR':'PAUSAR'};controls.querySelector('#n').onclick=()=>{localStorage.removeItem('MINICITY_V7');location.reload()};c.onpointerdown=e=>{drag=true;lx=e.clientX};onpointerup=()=>drag=false;onpointermove=e=>{if(drag){az+=(e.clientX-lx)*.008;lx=e.clientX}};c.onwheel=e=>{dist=Math.max(25,Math.min(100,dist+e.deltaY*.05))};c.onclick=e=>{let best=null,bd=30;people.forEach(p=>{const q=P(p.x,0,p.z),d=Math.hypot(q[0]-e.clientX,q[1]-e.clientY);if(d<bd){bd=d;best=p}});if(best){selected=best;panel.innerHTML='<b>'+best.name+' — morador '+(best.i+1)+'</b><br>Está caminhando pela rede de ruas<br>Destino: '+(best.target+1)+' • aprendizado e vida continuam'}};
function loop(){if(!paused){t+=.018;update();if((t*60|0)%240===0)save()}world();requestAnimationFrame(loop)}loop();
})()