(()=>{'use strict';
const old=document.getElementById('world');if(old)old.style.display='none';
const c=document.createElement('canvas');c.id='minicity3d';Object.assign(c.style,{position:'fixed',inset:0,width:'100vw',height:'100vh',display:'block',zIndex:1});document.body.style.cssText='margin:0;overflow:hidden';document.body.appendChild(c);
import('https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js').then(T=>{
const scene=new T.Scene();scene.background=new T.Color(0x91b9c8);scene.fog=new T.Fog(0x91b9c8,90,360);
const camera=new T.PerspectiveCamera(52,innerWidth/innerHeight,.1,800),renderer=new T.WebGLRenderer({canvas:c,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;
scene.add(new T.HemisphereLight(0xffffff,0x52694d,2.2));const sun=new T.DirectionalLight(0xffffff,3);sun.position.set(80,120,50);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun);
const world=new T.Group();scene.add(world);const M=c=>new T.MeshStandardMaterial({color:c,roughness:.72});
const box=(x,y,z,c,px,py,pz,p=world)=>{const m=new T.Mesh(new T.BoxGeometry(x,y,z),M(c));m.position.set(px,py,pz);m.castShadow=m.receiveShadow=true;p.add(m);return m};
const sph=(r,c,p)=>{const m=new T.Mesh(new T.SphereGeometry(r,16,12),M(c));m.castShadow=m.receiveShadow=true;p.add(m);return m};
function limb(p,a,b,r,c){const A=new T.Vector3(...a),B=new T.Vector3(...b),d=B.clone().sub(A),m=new T.Mesh(new T.CapsuleGeometry(r,Math.max(.05,d.length()-r*2),8,12),M(c));m.position.copy(A).add(B).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),d.normalize());m.castShadow=m.receiveShadow=true;p.add(m);return m}
box(170,1,125,0x8dac6e,0,-.5,0);box(14,.12,125,0x4b91b7,0,.08,-8);const lake=new T.Mesh(new T.CylinderGeometry(15,15,.15,48),M(0x4b99bc));lake.rotation.x=Math.PI/2;lake.scale.set(1,.48,1);lake.position.set(-37,.1,35);world.add(lake);
for(let i=0;i<70;i++){const a=i*2.41,r=12+(i%8)*3,x=-55+Math.cos(a)*r,z=-25+Math.sin(a)*r;box(.8,3+(i%3),.8,0x62452f,x,.5+(i%3)*.5,z);sph(2.4+(i%3)*.35,0x35683e,world).position.set(x,4.1+(i%3)*.4,z)}
for(let i=0;i<10;i++){const a=i*2.4,r=9+(i%3)*2,x=Math.cos(a)*r,z=Math.sin(a)*r,h=4+(i%3);box(7,h,6,[0xd8c4a2,0xc7d5c5,0xd6ae87][i%3],x,h/2,z);const roof=new T.Mesh(new T.ConeGeometry(5.4,3,4),M([0x8e493d,0x536b72,0x76533d][i%3]));roof.position.set(x,h+1.5,z);roof.rotation.y=Math.PI/4;roof.castShadow=true;world.add(roof);box(1.5,2,.12,0x51372b,x,1,z-3.06)}
box(28,.2,24,0xc7b97b,38,.1,30);for(let i=0;i<7;i++)box(.3,.3,22,0x769351,26+i*4,.3,30);box(24,8,20,0x777970,-38,4,27);box(20,6,16,0x4d514b,-38,8,27);
function human(i){const g=new T.Group(),skin=[0xd29a77,0x8c5c45,0xefbd99,0xb87655,0xa36b4d][i%5],shirt=[0x365d91,0x9b453c,0x477754,0xb88a43,0x76548d][i%5],pants=[0x29394b,0x4a4945,0x583e35,0x334c5e][i%4],hair=[0x201a17,0x4b3020,0x75603e,0x151515][i%4],shoe=0x202020,s=.9+(i%6)*.025;
g.scale.setScalar(s);g.userData={id:i,name:'Habitante-'+String(i+1).padStart(2,'0'),base:s,phase:i*.53};
const pelvis=new T.Group();pelvis.position.y=10;g.add(pelvis);const pm=sph(2.8,pants,pelvis);pm.scale.set(1.25,.7,.82);
const waist=new T.Group();waist.position.y=2.5;pelvis.add(waist);const torso=new T.Mesh(new T.CapsuleGeometry(3.15,5.8,10,16),M(shirt));torso.scale.set(.78,1,.58);torso.castShadow=true;waist.add(torso);
const chest=sph(3.0,shirt,waist);chest.scale.set(1.12,.48,.72);chest.position.y=2.1;
const neck=new T.Group();neck.position.y=7;waist.add(neck);const n=sph(1.05,skin,neck);n.scale.set(.9,1.2,.9);n.position.y=.45;
const head=sph(2.35,skin,neck);head.scale.set(.92,1.12,.9);head.position.y=3;const haircap=sph(2.4,hair,neck);haircap.scale.set(.98,.56,.94);haircap.position.set(0,4.35,0);
for(const x of [-.82,.82]){const eye=sph(.16,0x171717,neck);eye.position.set(x,3.15,2.02)}
const J={};
function arm(side){const q=side==='L'?-1:1,shoulder=new T.Group();shoulder.position.set(q*3.05,6.2,0);waist.add(shoulder);sph(1.05,skin,shoulder);const upper=new T.Group();shoulder.add(upper);limb(upper,[0,0,0],[0,-4.9,0],1.02,skin);const elbow=new T.Group();elbow.position.y=-4.9;upper.add(elbow);sph(.9,skin,elbow);const fore=new T.Group();elbow.add(fore);limb(fore,[0,0,0],[0,-4.7,0],.82,skin);const wrist=new T.Group();wrist.position.y=-4.7;fore.add(wrist);sph(.62,skin,wrist);const hand=sph(.82,skin,wrist);hand.scale.set(.72,1.05,.62);hand.position.y=-.75;J['shoulder'+side]=shoulder;J['elbow'+side]=elbow;J['wrist'+side]=wrist}
arm('L');arm('R');
function leg(side){const q=side==='L'?-1:1,hip=new T.Group();hip.position.set(q*1.5,0,0);pelvis.add(hip);sph(1.05,skin,hip);const thigh=new T.Group();hip.add(thigh);limb(thigh,[0,0,0],[0,-5.9,0],1.28,pants);const knee=new T.Group();knee.position.y=-5.9;thigh.add(knee);sph(1.02,skin,knee);const shin=new T.Group();knee.add(shin);limb(shin,[0,0,0],[0,-5.8,0],.92,pants);const ankle=new T.Group();ankle.position.y=-5.8;shin.add(ankle);sph(.7,skin,ankle);const foot=box(1.9,1.15,3.5,shoe,0,-.55,1.0,ankle);J['hip'+side]=hip;J['knee'+side]=knee;J['ankle'+side]=ankle}
leg('L');leg('R');g.userData.joints=['neck','shoulderL','elbowL','wristL','shoulderR','elbowR','wristR','hipL','kneeL','ankleL','hipR','kneeR','ankleR'];return g}
const people=[];for(let i=0;i<50;i++){const p=human(i),a=i*2.399,r=17+(i%8)*4;p.position.set(Math.cos(a)*r,0,Math.sin(a)*r);p.userData.vx=.012+(i%5)*.002;p.userData.vz=.01+(i%4)*.002;world.add(p);people.push(p)}
let selected=null,paused=true,t=0,az=.72,el=.62,dist=82,drag=false,lx=0,ly=0;
function save(){try{localStorage.setItem('MINICITY_3D_V3',JSON.stringify({t,people:people.map(p=>({x:p.position.x,z:p.position.z,r:p.rotation.y}))}))}catch(e){}}
function load(){try{const s=JSON.parse(localStorage.getItem('MINICITY_3D_V3'));if(s?.people?.length===50){s.people.forEach((q,i)=>{people[i].position.set(q.x,0,q.z);people[i].rotation.y=q.r||0});t=s.t||0;return true}}catch(e){}return false}
const restored=load();
const ui=document.createElement('div');ui.style='position:fixed;left:18px;top:18px;z-index:5;color:white;font:600 14px system-ui;text-shadow:0 2px 5px #000';ui.innerHTML='<b style="font-size:25px">MINICITY</b><br>50 HABITANTES • CORPOS 3D ARTICULADOS<br><span id="st">'+(restored?'CONTINUANDO':'PAUSADA')+'</span>';document.body.appendChild(ui);
const panel=document.createElement('div');panel.style='position:fixed;left:18px;bottom:18px;z-index:5;padding:13px 16px;background:#07110ddd;color:white;border-radius:10px;font:13px system-ui;min-width:270px';panel.innerHTML='<b>MINICITY</b><br>Selecione uma pessoa para observar';document.body.appendChild(panel);
const reset=document.createElement('button');reset.textContent='NOVO MUNDO';reset.style='position:fixed;right:18px;bottom:18px;z-index:6;padding:11px 16px;border:0;border-radius:9px;background:#813d34;color:white;font-weight:800;cursor:pointer';reset.onclick=()=>{localStorage.removeItem('MINICITY_3D_V3');location.reload()};document.body.appendChild(reset);
const help=document.createElement('div');help.style='position:fixed;right:18px;top:18px;z-index:5;padding:10px 13px;background:#07110ddd;color:white;border-radius:9px;font:12px system-ui';help.innerHTML='ARRASTE: câmera · RODA: zoom · ESPAÇO: pausar · CLIQUE: pessoa';document.body.appendChild(help);
c.addEventListener('pointerdown',e=>{drag=true;lx=e.clientX;ly=e.clientY});addEventListener('pointerup',()=>drag=false);addEventListener('pointermove',e=>{if(!drag)return;az-=(e.clientX-lx)*.008;el=Math.max(.2,Math.min(1.3,el+(e.clientY-ly)*.006));lx=e.clientX;ly=e.clientY});c.addEventListener('wheel',e=>dist=Math.max(25,Math.min(170,dist+e.deltaY*.07)),{passive:true});
c.addEventListener('click',e=>{const r=c.getBoundingClientRect(),v=new T.Vector2((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1),ray=new T.Raycaster();ray.setFromCamera(v,camera);const hits=ray.intersectObjects(people,true);if(!hits.length)return;let q=hits[0].object;while(q.parent&&!q.userData.id)q=q.parent;selected=q;people.forEach(p=>p.scale.setScalar(p.userData.base*(p===selected?1.13:1)));panel.innerHTML='<b>'+selected.userData.name+'</b><br>Humano articulado<br>13 articulações<br>Estado: '+(paused?'pausado':'caminhando')});
addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();paused=!paused;document.getElementById('st').textContent=paused?'PAUSADA':'EM EXECUÇÃO';save()}});
function animate(){requestAnimationFrame(animate);if(!paused){t+=.016;people.forEach((p,i)=>{const w=Math.sin(t*5+p.userData.phase),w2=-w;const u=p.userData;p.position.x+=u.vx;p.position.z+=u.vz;if(Math.abs(p.position.x)>65)u.vx*=-1;if(Math.abs(p.position.z)>48)u.vz*=-1;p.rotation.y=Math.atan2(u.vx,u.vz);u.shoulderL&&(u.shoulderL.rotation.z=-.08+w*.32);u.shoulderR&&(u.shoulderR.rotation.z=.08+w2*.32);u.elbowL&&(u.elbowL.rotation.z=-.15);u.elbowR&&(u.elbowR.rotation.z=.15);u.hipL&&(u.hipL.rotation.x=w*.42);u.hipR&&(u.hipR.rotation.x=w2*.42);u.kneeL&&(u.kneeL.rotation.x=Math.max(0,-w)*.55);u.kneeR&&(u.kneeR.rotation.x=Math.max(0,-w2)*.55);u.ankleL&&(u.ankleL.rotation.x=-Math.max(0,-w)*.22);u.ankleR&&(u.ankleR.rotation.x=-Math.max(0,-w2)*.22)});save()}
camera.position.set(Math.sin(az)*Math.cos(el)*dist,Math.sin(el)*dist,Math.cos(az)*Math.cos(el)*dist);camera.lookAt(0,6,0);renderer.render(scene,camera)}
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)});animate();if(!restored)setTimeout(()=>{paused=false;document.getElementById('st').textContent='EM EXECUÇÃO'},900);
}).catch(e=>{document.body.innerHTML='<div style="padding:40px;font:20px system-ui">Erro ao iniciar 3D: '+e+'</div>'})})()