(()=>{'use strict';
const old=document.getElementById('world');if(old)old.style.display='none';document.body.innerHTML='';document.body.style='margin:0;overflow:hidden;background:#91b9c9;font-family:system-ui';
const c=document.createElement('canvas');c.style='position:fixed;inset:0;width:100vw;height:100vh';document.body.appendChild(c);const x=c.getContext('2d');
const ui=document.createElement('div');ui.style='position:fixed;left:18px;top:16px;color:#fff;text-shadow:0 2px 5px #000;z-index:3';ui.innerHTML='<b style="font-size:26px;letter-spacing:.12em">MINICITY</b><br>50 HABITANTES • SOCIEDADE ARTIFICIAL • 3D';document.body.appendChild(ui);
const panel=document.createElement('div');panel.style='position:fixed;left:18px;bottom:18px;padding:12px 15px;background:#07110ddd;color:#fff;border-radius:10px;z-index:3;font-size:13px;min-width:280px';panel.innerHTML='<b>MINICITY</b><br>50 habitantes com corpos articulados<br>Arraste para girar • roda para aproximar';document.body.appendChild(panel);
const controls=document.createElement('div');controls.style='position:fixed;right:18px;bottom:18px;z-index:3';controls.innerHTML='<button id="p">PAUSAR</button> <button id="n">NOVO MUNDO</button>';document.body.appendChild(controls);controls.querySelectorAll('button').forEach(b=>b.style='padding:10px 14px;border:0;border-radius:8px;background:#18251b;color:#fff;font-weight:800');
function resize(){c.width=innerWidth*devicePixelRatio;c.height=innerHeight*devicePixelRatio;x.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}resize();addEventListener('resize',resize);
const names=['Ana','Bruno','Clara','Davi','Elena','Felipe','Gabriela','Hugo','Iara','Joao','Karina','Leo','Marta','Nuno','Olivia','Paulo','Rita','Sofia','Tiago','Vera','Yara','Zeca','Alice','Bia','Caio','Diana','Eva','Fabi','Gabi','Heitor','Ines','Julia','Lia','Miguel','Nina','Otavio','Pietro','Raquel','Sara','Theo','Ursula','Vitor','Wanda','Xavier','Yasmin','Zoe','Arthur','Beatriz','Celia','Diego'];
const people=names.map((name,i)=>{const a=i*2.399,r=10+(i%8)*2.7;return{name,i,x:Math.cos(a)*r,z:Math.sin(a)*r,vx:.018+(i%5)*.004,vz:.014+(i%4)*.004,phase:i*.71,rot:0}});
const houses=Array.from({length:10},(_,i)=>{const a=i*2.35,r=13+(i%3)*2.5;return{x:Math.cos(a)*r,z:Math.sin(a)*r,w:7,d:6,h:4.5+(i%3)}});
let paused=false,t=0,az=.72,dist=55,drag=false,lx=0,selected=null;
function P(X,Y,Z){const ca=Math.cos(az),sa=Math.sin(az),rx=X*ca-Z*sa,rz=X*sa+Z*ca;const scale=dist/(dist+rz+75);return [innerWidth/2+rx*scale*6,innerHeight/2+(Y-5)*scale*6,scale]}
function line(a,b,w,color){x.strokeStyle=color;x.lineWidth=w;x.lineCap='round';x.beginPath();x.moveTo(a[0],a[1]);x.lineTo(b[0],b[1]);x.stroke()}
function box(X,Z,w,d,h,color){const q=P(X,0,Z),s=q[2];x.fillStyle=color;x.fillRect(q[0]-w*s*3,q[1]-h*s*3,w*s*6,h*s*6);x.fillStyle='#74483d';x.beginPath();x.moveTo(q[0]-w*s*3,q[1]-h*s*3);x.lineTo(q[0],q[1]-(h+2)*s*3);x.lineTo(q[0]+w*s*3,q[1]-h*s*3);x.closePath();x.fill()}
function human(p){const q=P(p.x,0,p.z),s=q[2],sx=q[0],sy=q[1],w=Math.sin(t*5+p.phase),skin=['#d49b78','#8d6049','#efbe9a','#b87856','#a56d50'][p.i%5],shirt=['#365d91','#9b453c','#477754','#b88a43','#76548d'][p.i%5],pants=['#29394b','#4a4945','#583e35','#334c5e'][p.i%4];const H=28*s, S=1.0+(p.i%5)*.035;
function L(x1,y1,x2,y2,col,ww){line([sx+x1*s*S,sy+y1*s*S],[sx+x2*s*S,sy+y2*s*S],ww*s*S,col)}
L(-7,-18,-11-w*2,-9,shirt,5);L(7,-18,11+w*2,-9,shirt,5);L(-11-w*2,-9,-12-w*2,-1,skin,4);L(11+w*2,-9,12+w*2,-1,skin,4);
L(-4,0,-5+w*3,10,pants,6);L(4,0,5-w*3,10,pants,6);L(-5+w*3,10,-5+w*3,19,pants,5);L(5-w*3,10,5-w*3,19,pants,5);L(-5+w*3,19,-7+w*3,20,'#202020',5);L(5-w*3,19,7-w*3,20,'#202020',5);
x.fillStyle=shirt;x.beginPath();x.ellipse(sx,sy-8*s*S,7*s*S,9*s*S,0,0,7);x.fill();x.fillStyle=skin;x.beginPath();x.arc(sx,sy-25*s*S,6*s*S,0,7);x.fill();x.fillStyle='#201a17';x.beginPath();x.arc(sx,sy-28*s*S,6*s*S,Math.PI,Math.PI*2);x.fill();x.fillStyle='#111';x.beginPath();x.arc(sx-2*s,sy-25*s,0.8*s,0,7);x.arc(sx+2*s,sy-25*s,.8*s,0,7);x.fill();
return [sx,sy-H*.9,s*7]}
function world(){x.clearRect(0,0,innerWidth,innerHeight);x.fillStyle='#86ad69';x.fillRect(0,0,innerWidth,innerHeight);const r=P(0,0,0);x.fillStyle='#4d94b8';x.fillRect(r[0]-70,r[1]-innerHeight/2,140,innerHeight);for(let i=0;i<70;i++){const a=i*2.399,rr=15+(i%9)*2.8,X=-55+Math.cos(a)*rr,Z=-28+Math.sin(a)*rr,q=P(X,0,Z);x.fillStyle='#654831';x.fillRect(q[0]-2,q[1]-18,q[2]*4,q[2]*18);x.fillStyle='#397044';x.beginPath();x.arc(q[0],q[1]-20,q[2]*13,0,7);x.fill()}houses.forEach(h=>box(h.x,h.z,h.w,h.d,h.h,['#d7c09a','#c9d6c4','#d5ad83'][h.i%3]));people.slice().sort((a,b)=>a.z-b.z).forEach(human)}
function save(){try{localStorage.setItem('MINICITY_V6',JSON.stringify(people.map(p=>({x:p.x,z:p.z}))));}catch(e){}}try{const s=JSON.parse(localStorage.getItem('MINICITY_V6'));if(s?.length===50)s.forEach((q,i)=>{people[i].x=q.x;people[i].z=q.z})}catch(e){}
controls.querySelector('#p').onclick=()=>{paused=!paused;controls.querySelector('#p').textContent=paused?'CONTINUAR':'PAUSAR'};controls.querySelector('#n').onclick=()=>{localStorage.removeItem('MINICITY_V6');location.reload()};c.onpointerdown=e=>{drag=true;lx=e.clientX};onpointerup=()=>drag=false;onpointermove=e=>{if(drag){az+=(e.clientX-lx)*.008;lx=e.clientX}};c.onwheel=e=>{dist=Math.max(25,Math.min(100,dist+e.deltaY*.05))};c.onclick=e=>{let best=null,bd=35;people.forEach(p=>{const q=P(p.x,0,p.z),d=Math.hypot(q[0]-e.clientX,q[1]-e.clientY);if(d<bd){bd=d;best=p}});if(best){selected=best;panel.innerHTML='<b>'+best.name+'-'+(best.i+1)+'</b><br>Corpo humano 3D articulado<br>Ombros • cotovelos • punhos<br>Quadris • joelhos • tornozelos'}};
function loop(){if(!paused){t+=.018;people.forEach(p=>{p.x+=p.vx;p.z+=p.vz;if(Math.abs(p.x)>82)p.vx*=-1;if(Math.abs(p.z)>58)p.vz*=-1;p.rot=Math.atan2(p.vx,p.vz)});if((t*60|0)%180===0)save()}world();requestAnimationFrame(loop)}loop();
})()